export type Lang = 'zh' | 'en';
export const langs: Lang[] = ['zh', 'en'];

export const ui = {
  zh: {
    'nav.home': '首页',
    'nav.products': '产品中心',
    'nav.solutions': '解决方案',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.search': '搜索',
    'lang.switch': 'EN',
    'home.featured': '常用产品',
    'home.categories': '产品分类',
    'home.why': '为什么选择我们',
    'home.cta': '获取报价与选型支持',
    'home.ctaDesc': '提供工况参数，工程师 24 小时内给出选型方案与报价。',
    'btn.inquiry': '立即询价',
    'btn.more': '查看详情',
    'btn.all': '全部产品',
    'btn.datasheet': '下载产品资料',
    'products.title': '产品中心',
    'products.all': '全部',
    'products.filter': '筛选',
    'products.keyword': '输入型号或名称',
    'products.count': '共 {n} 个产品',
    'products.empty': '没有符合条件的产品',
    'product.specs': '技术参数',
    'product.features': '产品特点',
    'product.applications': '应用领域',
    'product.related': '相关产品',
    'product.model': '型号',
    'form.title': '在线询价',
    'form.name': '姓名',
    'form.company': '公司',
    'form.phone': '电话',
    'form.email': '邮箱',
    'form.product': '意向产品',
    'form.message': '需求描述（介质、口径、量程、数量等）',
    'form.submit': '提交',
    'form.sending': '提交中…',
    'form.ok': '提交成功，我们将尽快与您联系。',
    'form.fail': '提交失败，请直接致电或发送邮件。',
    'contact.phone': '电话',
    'contact.email': '邮箱',
    'contact.address': '地址',
    'contact.wechat': '微信咨询',
    'search.title': '站内搜索',
    'search.devNote': '搜索索引在执行 npm run build 后生成。',
    'footer.rights': '版权所有',
    'notfound.title': '页面不存在',
    'notfound.back': '返回首页',
  },
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.solutions': 'Solutions',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.search': 'Search',
    'lang.switch': '中文',
    'home.featured': 'Featured Products',
    'home.categories': 'Product Categories',
    'home.why': 'Why Choose Us',
    'home.cta': 'Get a Quote & Sizing Support',
    'home.ctaDesc': 'Send us your process data and our engineers will reply with a solution within 24 hours.',
    'btn.inquiry': 'Get a Quote',
    'btn.more': 'Details',
    'btn.all': 'All Products',
    'btn.datasheet': 'Download Datasheet',
    'products.title': 'Products',
    'products.all': 'All',
    'products.filter': 'Filter',
    'products.keyword': 'Model or name',
    'products.count': '{n} products',
    'products.empty': 'No matching products',
    'product.specs': 'Specifications',
    'product.features': 'Features',
    'product.applications': 'Applications',
    'product.related': 'Related Products',
    'product.model': 'Model',
    'form.title': 'Inquiry',
    'form.name': 'Name',
    'form.company': 'Company',
    'form.phone': 'Phone',
    'form.email': 'Email',
    'form.product': 'Product of interest',
    'form.message': 'Requirements (medium, size, range, quantity…)',
    'form.submit': 'Submit',
    'form.sending': 'Sending…',
    'form.ok': 'Thank you! We will get back to you shortly.',
    'form.fail': 'Submission failed. Please call or email us directly.',
    'contact.phone': 'Phone',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.wechat': 'WeChat',
    'search.title': 'Search',
    'search.devNote': 'The search index is generated by npm run build.',
    'footer.rights': 'All rights reserved',
    'notfound.title': 'Page not found',
    'notfound.back': 'Back to home',
  },
} as const;

export type UiKey = keyof (typeof ui)['zh'];

export const useT = (lang: Lang) => (key: UiKey, vars: Record<string, string | number> = {}) =>
  Object.entries(vars).reduce<string>((s, [k, v]) => s.replace(`{${k}}`, String(v)), ui[lang][key]);

export const localePath = (lang: Lang, path: string) => {
  const p = path.startsWith('/') ? path : `/${path}`;
  return lang === 'zh' ? p : `/en${p}`;
};

export const switchLangPath = (pathname: string, to: Lang) => {
  const bare = pathname.replace(/^\/en(\/|$)/, '/');
  return localePath(to, bare);
};

export const pick = <T>(v: { zh: T; en: T }, lang: Lang): T => v[lang];
